controller:
  ingressClassResource:
    name: external-nginx
    controllerValue: k8s.io/external-nginx
  admissionWebhooks:
    create: true
    patch:
      enabled: true
      name: external-webhook
    # Restrict webhook to "external" class
    objectSelector:
      matchExpressions:
        - key: class
          operator: In
          values: [external-nginx]
  service:
    enabled: false
  allowSnippetAnnotations: true
  config: 
    annotations-risk-level: critical
  hostNetwork: false
  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
  dnsPolicy: ClusterFirstWithHostNet
  extraVolumes:
    - name: nginx-cache
      emptyDir: {}
  extraVolumeMounts:
    - name: nginx-cache
      mountPath: /tmp/nginx-cache
  publishService:
    enabled: false
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: type
                operator: In
                values:
                  - ingress
                  - cloud